server:
  port: 8080
spring:
  mvc:
    servlet:
      load-on-startup: ${spring-mvc-servlet-load-on-startup:1}
      path: ${spring-mvc-servlet-path:/api}

webui:
  servlet:
    load-on-startup: ${webui-servlet-load-on-startup:2}
    path: ${webui-servlet-path:/*}
  configuration-type: ${webui-configuration-type:DEVELOPMENT}
  csrf: ${webui-csrf:false}
  wicket-factory: com.senior.cyber.frmk.html.factory.WicketFactory
  admin-lte: ${webui-admin-lte:/Users/socheatkhauv/github/ColorlibHQ/AdminLTE}
