server:
  port: 8080
spring:
  mvc:
    servlet:
      load-on-startup: ${override.spring.mvc.servlet.load-on-startup:1}
      path: ${override.spring.mvc.servlet.path:/api}
webui:
  servlet:
    load-on-startup: ${override.webui.servlet.load-on-startup:2}
    path: ${override.webui.servlet.path:/*}
  configuration-type: ${override.webui.configuration-type:DEVELOPMENT}
  csrf: ${override.webui.csrf:false}
  wicket-factory: com.senior.cyber.frmk.html.factory.WicketApplication
  admin-lte: /Users/socheatkhauv/github/ColorlibHQ/AdminLTE